In [ ]:
3 + 5*4

In [2]:
weight_kg = 60.0
weight_kg_text = 'weight in kilograms:'

In [3]:
print(weight_kg)

60.0


In [4]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60.0


In [6]:
print(weight_kg_text, weight_kg/0.4535)

weight in kilograms: 132.3042998897464


In [7]:
import numpy as np

In [13]:
#help(np.loadtxt)

In [8]:
np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [15]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [16]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [18]:
#dir(data)

In [ ]:
print(type(data))

In [ ]:
print(data.dtype)

In [ ]:
print(data.shape)

In [ ]:
print('first value in data:', data[0, 0])

In [ ]:
print('middle value in data:', data[30, 20])

In [ ]:
print(data[0:4, 0:10])

In [ ]:
import time
print(time.ctime())

In [ ]:
import matplotlib.pyplot
image = matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show()
%matplotlib inline

In [ ]:
ave_inflammation = np.mean(data, axis=0)
ave_plot = matplotlib.pyplot.plot(ave_inflammation)
matplotlib.pyplot.show()